export type ProductSite = "musinsa.com" | "youthisyours.net" | "sansangear.com" | "adererror.com" | "satur.co.kr" | "ssfshop.com" | "29cm.co.kr" | "unknown";

export type ProductDraft = {
  site: ProductSite;
  sourceUrl: string;
  titleKo: string;
  title: string;
  titleManuallyEdited?: boolean;
  titleEn?: string;
  translatedTitle?: string;
  brand: string;
  brandDisplayName?: string;
  brandId?: string;
  price: number;
  referencePrice?: number;
  sellingPrice?: number;
  category?: string;
  season?: string;
  theme?: string;
  unisex?: boolean;
  colors: string[];
  sizes: string[];
  sizeMeasurements?: Record<string, Record<string, string>>;
  sizeChartHtml?: string;
  sizeTableData?: ColorSizeRow[];
  stockData?: Record<string, StockStatus>;
  optionStockMap?: Record<string, StockStatus>;
  colorSystemId?: string;
  colorSystemMap?: Record<string, string>;
  images: string[];
  brandLogo?: string;
  editedImage?: string;
  uploadedImageUrls?: string[];
  buymaProductId?: string;
  control?: string;
  publicStatus?: string;
  productCode: string;
  skuNumber?: string;
  purchaseSourceDescription15?: string;
  modelNumber?: string;
  brandModelMemo1?: string;
  brandModelNumber2?: string;
  brandModelMemo2?: string;
  brandModelNumber3?: string;
  brandModelMemo3?: string;
  brandModelNumber4?: string;
  brandModelMemo4?: string;
  brandModelNumber5?: string;
  brandModelMemo5?: string;
  brandModelNumber6?: string;
  brandModelMemo6?: string;
  brandModelNumber7?: string;
  brandModelMemo7?: string;
  brandModelNumber8?: string;
  brandModelMemo8?: string;
  brandModelNumber9?: string;
  brandModelMemo9?: string;
  brandModelNumber10?: string;
  brandModelMemo10?: string;
  tags?: string;
  purchaseDeadline?: string;
  purchaseQuantity?: string | number;
  shippingMethod?: string;
  purchaseArea?: string;
  purchaseCity?: string;
  purchaseShop?: string;
  purchaseName1?: string;
  purchaseUrl1?: string;
  purchaseSourceDescription1?: string;
  purchaseName2?: string;
  purchaseUrl2?: string;
  purchaseSourceDescription2?: string;
  purchaseName3?: string;
  purchaseUrl3?: string;
  purchaseSourceDescription3?: string;
  purchaseName4?: string;
  purchaseUrl4?: string;
  purchaseSourceDescription4?: string;
  purchaseName5?: string;
  purchaseUrl5?: string;
  purchaseSourceDescription5?: string;
  purchaseName6?: string;
  purchaseUrl6?: string;
  purchaseSourceDescription6?: string;
  purchaseName7?: string;
  purchaseUrl7?: string;
  purchaseSourceDescription7?: string;
  purchaseName8?: string;
  purchaseUrl8?: string;
  purchaseSourceDescription8?: string;
  purchaseName9?: string;
  purchaseUrl9?: string;
  purchaseSourceDescription9?: string;
  purchaseName10?: string;
  purchaseUrl10?: string;
  purchaseSourceDescription10?: string;
  purchaseName11?: string;
  purchaseUrl11?: string;
  purchaseSourceDescription11?: string;
  purchaseName12?: string;
  purchaseUrl12?: string;
  purchaseSourceDescription12?: string;
  purchaseName13?: string;
  purchaseUrl13?: string;
  purchaseSourceDescription13?: string;
  purchaseName14?: string;
  purchaseUrl14?: string;
  purchaseSourceDescription14?: string;
  purchaseName15?: string;
  purchaseUrl15?: string;
  shippingArea?: string;
  shippingCity?: string;
  taxIncluded?: string;
  listingMemo?: string;
  descriptionKo?: string;
  description?: string;
  stockStatus?: StockStatus | "normal" | "soldout";
  extractedAt: string;
};

export type StockStatus = "0" | "1" | "2";

export type ColorSizeRow = {
  color: string;
  colorSystemId: string;
  size: string;
  sizeTypeId?: string;
  supplement?: string;
  stock: StockStatus;
};

export type BuymaDescriptionPlacement = "before" | "after";

export type BuymaSettings = {
  marginRate: number;
  exchangeRate: number;
  defaultReferencePrice: number;
  productTitlePrefix: string;
  productDescriptionPrefix: string;
  productDescriptionPlacement: BuymaDescriptionPlacement;
  shippingMethods: BuymaShippingMethod[];
  shippingMethodsInitialized: boolean;
  shippingMethodsVersion: number;
  customColors: string;
  customSizes: string;
  imgbbApiKey: string;
  imageServerUrl: string;
  imageServerApiKey: string;
  enableImageUpload: boolean;
};

export type BuymaShippingMethod = {
  id: string;
  label: string;
};

export type CsvBundle = {
  itemsCsv: string;
  colorSizesCsv: string;
};

export type ExtractProductResponse =
  | { ok: true; product: ProductDraft }
  | { ok: false; error: string };
